apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: service:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SERVICE_NAME
            value: service2
        ports:
        - containerPort: 5000
      - name: service2-sidecar
        image: sidecar:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SERVICE_NAME
            value: service2
        ports:
        - containerPort: 5001
