apiVersion: apps/v1
kind: Deployment
metadata:
  name: service5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service5
  template:
    metadata:
      labels:
        app: service5
    spec:
      containers:
      - name: service5
        image: service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
