apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: service:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SERVICE_NAME
            value: service1
        ports:
        - containerPort: 5000
      - name: service1-sidecar
        image: sidecar:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SERVICE_NAME
            value: service1
        ports:
        - containerPort: 5001
