apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: service:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SERVICE_NAME
            value: service3
        ports:
        - containerPort: 5000
      - name: service3-sidecar
        image: sidecar:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SERVICE_NAME
            value: service3
        ports:
        - containerPort: 5001
