apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  type: NodePort
  ports:
    - name: http
      port: 7474  # Neo4j HTTP port
      targetPort: 7474
      nodePort: 30074
    - name: bolt
      port: 7687  # Neo4j Bolt port
      targetPort: 7687
      nodePort: 30687
  selector:
    app: neo4j  # Ensure this matches the labels of your Neo4j pod

